# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'react-swift-test' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for react-swift-test

  target 'react-swift-testTests' do
    inherit! :search_paths
    # Pods for testing
    pod 'ReSwift'
    pod 'RxSwift',    '~> 4.0'
    pod 'RxCocoa',    '~> 4.0'
  end

  target 'react-swift-testUITests' do
    inherit! :search_paths
    # Pods for testing
    pod 'ReSwift'
    pod 'RxSwift',    '~> 4.0'
    pod 'RxCocoa',    '~> 4.0'
  end

end
